apiVersion: v1
kind: ServiceAccount
metadata:
  name: terminal
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terminal:cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: terminal
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: terminal
  name: terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminal
  template:
    metadata:
      labels:
        app: terminal
    spec:
      serviceAccountName: terminal
      containers:
        - name: terminal
          image: harbor.beautytiger.home/beautytiger/k8s-web-terminal
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 10Mi
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: terminal
  name: terminal
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: terminal
  type: NodePort
